# This is a basic workflow to help you get started with Actions

name: Daily File Upload

# Controls when the workflow will run
on:
  schedule:
        # Runs at 00:00 UTC every day
        - cron: '0 5 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload-file:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Create or modify file
            run: |
              echo "This file was updated on $(date)" > daily_report.txt

          - name: Configure Git
            run: |
               git config user.name 'github-actions[bot]'
               git config user.email 'github-actions[bot]@users.noreply.github.com'

          - name: Commit and push
            run : |
               git add daily_report.txt
               git commit -m "daily update: $(date)"
               git push
