
name: Daily File Upload

on:
  schedule:
        - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  upload-file:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Create or modify file
            run: |
              echo "This file was updated on $(date)" > daily_report.txt

          - name: Configure Git
            run: |
               git config user.name 'github-actions[bot]'
               git config user.email 'github-actions[bot]@users.noreply.github.com'

          - name: Commit and push
            run : |
               git add daily_report.txt
               git commit -m "daily update: $(date)"
               git push
